name = "MP3"
uuid = "cd409658-5b1a-491f-921a-81bcdb86ea62"
version = "1.0.1"

[deps]
BinDeps = "9e28174c-4ba2-5203-b857-d8d62c4213ee"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
SampledSignals = "bd7594eb-a658-542f-9e75-4c4d8908c167"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
BinDeps = "1"
FileIO = "1.2.4"
SampledSignals = "2.1"
julia = "1.3"
